name: Mythinizen
version: '${project.version}'
main: aduvip.mythinizen.Mythinizen
description: Some Added APi for Mythicmobs,ModelEngine,Denizen
api-version: 1.20
commands:
  tt:
    description: tt
    usage: /tt
softdepend:
  - MythicMobs
  - ModelEngine
  - Denizen